const $ = (id) => document.getElementById(id);
const messageFor = (result) => ({ API_KEY_INVALID: "The OpenAI API key was rejected.", TUNNEL_PERMISSION_DENIED: "The API key cannot access this tunnel. Use Tunnels: Read + Use.", TUNNEL_NOT_FOUND: "The tunnel could not be found.", NETWORK_ERROR: "ResearchTube could not reach OpenAI." }[result.errorCode] || result.message || "Connection test failed.");
async function call(message) { return chrome.runtime.sendMessage(message); }
function escapeHtml(value) { const element = document.createElement("span"); element.textContent = value; return element.innerHTML; }
function renderResult(result) { const box = $("test-result"); box.hidden = false; box.className = result.ok ? "ok" : "error"; box.innerHTML = result.ok ? "<strong>Connection successful.</strong><br>✓ API key accepted<br>✓ Tunnel found" : `<strong>${escapeHtml(messageFor(result))}</strong>${result.detail ? `<details><summary>Technical details</summary>${escapeHtml(result.detail)}</details>` : ""}`; }
function formatTest(test) { if (!test) return "No connection test has been run yet."; const when = new Date(test.timestamp).toLocaleString(); return test.success ? `Last connection test: Successful — ${when}` : `Last connection test: Failed — ${when}`; }
const EXTERNAL_LINK_ICON = '<svg class="external-link-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M14 3h7v7M21 3l-9 9M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"/></svg>';
async function load() { const state = await call({ type: "status" }); $("tunnel").value = state.tunnelId || ""; $("tunnel-copy").textContent = state.tunnelId || "Tunnel ID not configured"; $("key").placeholder = state.apiKeyPresent ? "••••••••••••••••" : "sk-…"; $("key-hint").innerHTML = state.apiKeyPresent ? `An API key is saved locally. Enter a new value here only to replace it. Open <a href="#" data-open="apiKeys">OpenAI API Keys ${EXTERNAL_LINK_ICON}</a>` : `Use a separate Restricted key with Tunnels: Read + Use. Open <a href="#" data-open="apiKeys">OpenAI API Keys ${EXTERNAL_LINK_ICON}</a>`; $("status").textContent = formatTest(state.lastConnectionTest); $("version").textContent = chrome.runtime.getManifest().version; bindExternalLinks(); }
async function save() { const result = await call({ type: "save-connection", payload: { tunnelId: $("tunnel").value, apiKey: $("key").value } }); if (!result.ok) renderResult(result); else { $("key").value = ""; await load(); } return result; }
$("save").addEventListener("click", save);
$("test").addEventListener("click", async () => { $("test").disabled = true; $("test").textContent = "Testing…"; const saved = await save(); const result = saved.ok ? await call({ type: "test-connection" }) : saved; renderResult(result); await load(); $("test").disabled = false; $("test").textContent = "Test connection"; });
$("clear").addEventListener("click", async () => { if (!confirm("Clear the saved OpenAI API key from this browser?")) return; await call({ type: "clear-api-key" }); $("key").value = ""; $("test-result").hidden = true; await load(); });
function bindExternalLinks() { document.querySelectorAll("[data-open]").forEach((link) => { if (link.dataset.bound) return; link.dataset.bound = "true"; link.addEventListener("click", (event) => { event.preventDefault(); call({ type: "open-external", target: link.dataset.open }); }); }); }
$("copy-tunnel").addEventListener("click", async () => { const tunnelId = $("tunnel").value.trim(); if (!tunnelId) return; await navigator.clipboard.writeText(tunnelId); $("copy-tunnel").textContent = "Copied"; setTimeout(() => { $("copy-tunnel").textContent = "Copy Tunnel ID"; }, 1400); });
load();
