import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const widget = await readFile(new URL("../ui/capture-frame-widget-v20.html", import.meta.url), "utf8");

assert.match(widget, /researchtube_get_capture_frame_image/);
assert.match(widget, /workspacePath/);
assert.match(widget, /window\.openai/);
assert.match(widget, /uploadFile\(imageFile, \{ library: true \}\)/);
assert.match(widget, /imageIds/);
assert.match(widget, /toolResponseMetadata/);
assert.match(widget, /openai:set_globals/);
assert.match(widget, /event\?\.detail\?\.globals\?\.toolOutput/);
assert.match(widget, /createImageBitmap/);
assert.match(widget, /getContext\("2d"\)/);
assert.match(widget, /<canvas id="image"/);
assert.match(widget, /<span class="brand-name">ResearchTube<\/span>/);
assert.match(widget, /captured video frame in workspace/);
assert.match(widget, /Captured frame unavailable/);
assert.match(widget, /workspace image is no longer available/);
assert.match(widget, /Local Agent is unavailable/);
assert.match(widget, /Check the Local Agent and workspace image file\./);
assert.match(widget, /overflow-wrap: anywhere/);
assert.match(widget, /id="copy-path"/);
assert.match(widget, /id="refresh-frame"/);
assert.match(widget, /notifyIntrinsicHeight/);
assert.match(widget, /showCopyBadge/);
assert.match(widget, /action-badge/);
assert.match(widget, /researchtube_copy_capture_frame_path/);
assert.match(widget, /dataTransfer/);
assert.match(widget, /dragstart/);
assert.match(widget, /dataTransfer\.items\.add\(file\)/);
assert.match(widget, /effectAllowed = "copy"/);
assert.match(widget, /makeDragFile/);
assert.match(widget, /new File\(\[blob\], dragFileName/);
assert.match(widget, /requestedLibrarySave/);
assert.match(widget, /toolInput\?\.delivery/);
assert.match(widget, /uploaded\?\.id/);
assert.match(widget, /const pattern = \/\\\[yt_/);
assert.match(widget, /youtube-video-link/);
assert.match(widget, /external\(\{ href, redirectUrl: false \}\)/);
assert.match(widget, /requestedTimestampSeconds\.toFixed\(3\)/);
assert.match(widget, /t = \$\{frame\.requestedTimestampSeconds/);
assert.doesNotMatch(widget, /researchtube_copy_capture_frame_image/);
assert.doesNotMatch(widget, /researchtube_download_capture_frame/);
assert.doesNotMatch(widget, /id="download-image"/);
assert.doesNotMatch(widget, /id="copy-image"/);
assert.doesNotMatch(widget, /id="copy-path-direct"/);
assert.doesNotMatch(widget, /navigator\.clipboard/);
assert.doesNotMatch(widget, /ClipboardItem/);
assert.doesNotMatch(widget, /callLocalExtensionAction/);
assert.doesNotMatch(widget, /getFileDownloadUrl/);
assert.doesNotMatch(widget, /library: false/);
assert.doesNotMatch(widget, /URL\.createObjectURL/);
assert.doesNotMatch(widget, /image\.src\s*=/);
assert.match(widget, /https:\/\/www\.youtube\.com\/watch\?v=/);
console.log("capture frame widget: ok");
