import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const widget = await readFile(new URL("../ui/capture-frame-widget-v24.html", import.meta.url), "utf8");

assert.match(widget, /researchtube_get_capture_frame_image/);
assert.match(widget, /workspacePath/);
assert.match(widget, /window\.openai/);
assert.match(widget, /openai:set_globals/);
assert.match(widget, /publicUrl/);
assert.match(widget, /Public image URL/);
assert.match(widget, /toolResponseMetadata/);
assert.match(widget, /captureFrameImageBase64/);
assert.match(widget, /createImageBitmap/);
assert.match(widget, /getContext\("2d"\)/);
assert.match(widget, /<canvas id="image"/);
assert.match(widget, /youtube-video-link/);
assert.match(widget, /researchtube_copy_capture_frame_path/);
assert.match(widget, /id="copy-frame-name"/);
assert.match(widget, /<g transform="translate\(12 12\)">/);
assert.match(widget, /refreshing/);
assert.match(widget, /overflow-wrap: anywhere/);
assert.doesNotMatch(widget, /researchtube_copy_capture_frame_image/);
assert.doesNotMatch(widget, /researchtube_download_capture_frame/);
assert.doesNotMatch(widget, /id="download-image"/);
assert.doesNotMatch(widget, /id="copy-image"/);
assert.doesNotMatch(widget, /id="copy-path-direct"/);
assert.doesNotMatch(widget, /navigator\.clipboard/);
assert.doesNotMatch(widget, /ClipboardItem/);
assert.doesNotMatch(widget, /callLocalExtensionAction/);
assert.doesNotMatch(widget, /getFileDownloadUrl/);
assert.doesNotMatch(widget, /uploadFile/);
assert.doesNotMatch(widget, /imageIds/);
assert.doesNotMatch(widget, /sendFollowUpMessage/);
assert.doesNotMatch(widget, /Library/);
assert.doesNotMatch(widget, /dragstart/);
assert.doesNotMatch(widget, /dataTransfer/);
assert.doesNotMatch(widget, /makeDragFile/);
assert.doesNotMatch(widget, /dragFile/);
assert.doesNotMatch(widget, /draggable=/);
console.log("capture frame widget: ok");
