import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const widget = await readFile(new URL("../ui/capture-frame-widget-v12.html", import.meta.url), "utf8");

assert.match(widget, /researchtube_get_capture_frame_image/);
assert.match(widget, /workspacePath/);
assert.match(widget, /window\.openai/);
assert.match(widget, /uploadFile\(file, \{ library: true \}\)/);
assert.match(widget, /imageIds/);
assert.match(widget, /toolResponseMetadata/);
assert.match(widget, /openai:set_globals/);
assert.match(widget, /event\?\.detail\?\.globals\?\.toolOutput/);
assert.match(widget, /createImageBitmap/);
assert.match(widget, /getContext\("2d"\)/);
assert.match(widget, /<canvas id="image"/);
assert.match(widget, /ResearchTube<\/div>/);
assert.match(widget, /Captured frame unavailable/);
assert.match(widget, /workspace image is no longer available/);
assert.match(widget, /Local Agent is unavailable/);
assert.match(widget, /Check the Local Agent and workspace image file\./);
assert.match(widget, /overflow-wrap: anywhere/);
assert.match(widget, /justify-content: flex-start/);
assert.match(widget, /id="download-image"/);
assert.match(widget, /id="copy-image"/);
assert.match(widget, /id="copy-path"/);
assert.match(widget, /id="refresh-frame"/);
assert.match(widget, /notifyIntrinsicHeight/);
assert.match(widget, /researchtube_copy_capture_frame_image/);
assert.match(widget, /researchtube_copy_capture_frame_path/);
assert.match(widget, /researchtube_download_capture_frame/);
assert.doesNotMatch(widget, /navigator\.clipboard/);
assert.doesNotMatch(widget, /URL\.createObjectURL/);
assert.doesNotMatch(widget, /getFileDownloadUrl/);
assert.doesNotMatch(widget, /openExternal/);
assert.doesNotMatch(widget, /library: false/);
assert.doesNotMatch(widget, /image\.src\s*=/);
assert.doesNotMatch(widget, /https?:\/\//);
console.log("capture frame widget: ok");
