import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const [background, manifest] = await Promise.all([
  readFile(new URL("../background.js", import.meta.url), "utf8"),
  readFile(new URL("../manifest.json", import.meta.url), "utf8")
]);
const parsedManifest = JSON.parse(manifest);

assert.ok(parsedManifest.permissions.includes("debugger"));
assert.ok(parsedManifest.host_permissions.includes("https://chatgpt.com/*"));
assert.match(background, /active: false/);
assert.match(background, /Page\.setInterceptFileChooserDialog/);
assert.match(background, /Page\.fileChooserOpened/);
assert.match(background, /DOM\.setFileInputFiles/);
assert.match(background, /chrome\.debugger\.detach/);
assert.match(background, /\[ResearchTube CDP\]/);
assert.match(background, /Composer file-input inspection/);
assert.match(background, /cdpAbsoluteFilePath/);
assert.match(background, /cdpWaitForStableComposer/, "first attachment must wait for a stable Composer, not merely tab load");
assert.match(background, /CDP_COMPOSER_SETTLE_MS/, "Composer readiness must include a stability interval");
assert.match(background, /cdpOpenStableFileChooser/, "a missed chooser event must be retried without requiring a new tab");
assert.match(background, /CDP_FILE_CHOOSER_ATTEMPTS/, "chooser retry count must be bounded");
assert.match(background, /result\?\.value === true/, "page-condition waits must inspect the CDP evaluation value");
assert.match(background, /cdpWaitForAttachmentAccepted/, "attachment completion must use Composer file acceptance, not only visible preview text");
assert.match(background, /input\.files/, "file-input selection must be accepted as browser-level attachment evidence");
assert.match(background, /drainLibraryStoreQueue/, "Library batches must share one serialized service-tab queue");
assert.match(background, /cdpAttachFilesNow/, "the queued public entrypoint must serialize the CDP lifecycle");
assert.match(background, /libraryStoreMaxFiles/, "a Composer batch must use the configured file count");
assert.match(background, /libraryStoreQueue/, "Library batches must be queued independently");
assert.match(background, /DOM\.setFileInputFiles", \{ files: filePaths/, "one chooser operation must receive the whole batch");
assert.match(background, /cdpSendAttachedFiles/, "the queued file batch must still be sent through ChatGPT");
assert.match(background, /cdpClickEnabledSendButton/, "all Composer sends must use the same browser-level click helper");
assert.match(background, /Input\.dispatchMouseEvent/, "the shortcut must dispatch trusted browser mouse input to ChatGPT Send");
assert.match(background, /mousePressed/, "the send click must include a press event");
assert.match(background, /mouseReleased/, "the send click must include a release event");
assert.match(background, /describeYouTubeVideoInChatGPT/, "the popup video shortcut must open a dedicated ChatGPT tab");
assert.match(background, /DESCRIBE_VIDEO_DUPLICATE_WINDOW_MS/, "the shortcut must suppress accidental duplicate description requests");
assert.match(background, /Suppressed duplicate video-description request/, "duplicate suppression must be visible in the CDP log");
assert.match(background, /url: "https:\/\/chatgpt\.com\/", active: false/, "Describe this video must keep the user on the active YouTube tab");
assert.match(background, /canonicalYouTubeVideoUrl/, "the shortcut must accept only a canonical single-video URL");
assert.match(background, /describeYouTubeVideoTitle/, "the shortcut must add the current YouTube title to make automatic chat titles meaningful");
assert.doesNotMatch(background, /currentDescribeYouTubeVideo/, "the shortcut must not replace the popup's current-tab snapshot with player state");
assert.match(background, /shortMatch = url\.pathname\.match/, "the shortcut must normalize a YouTube Short to its video ID");
assert.match(background, /Open one YouTube video or Short/, "the shortcut must describe ordinary videos and Shorts");
assert.match(background, /@ResearchTube \$\{videoTitle\} \$\{videoUrl\} Study the video and tell me what it is about in my language\./, "the shortcut must use the requested title-first one-line prompt without URL punctuation");
assert.match(background, /cdpSetComposerText\(chatTab\.id, prompt\)/, "the shortcut must place its prompt in Composer");
assert.match(background, /Input\.insertText/, "the shortcut must insert its complete prompt immediately");
assert.match(background, /CDP_COMPOSER_PROMPT_ATTEMPTS = 4/, "the shortcut must allow four complete prompt replacement attempts");
assert.match(background, /CDP_COMPOSER_PROMPT_RETRY_DELAY_MS = 2_000/, "the shortcut must wait two seconds before each replacement attempt");
assert.match(background, /async function cdpClearComposerDraft\(tabId\)/, "the shortcut must clear a restored draft before inserting a prompt");
assert.match(background, /CDP_SELECT_COMPOSER_CONTENTS_EXPRESSION/, "draft cleanup must select Composer contents using the existing normal selection path");
assert.match(background, /CDP_COMPOSER_EMPTY_EXPRESSION/, "each cleanup must verify that Composer is empty");
assert.doesNotMatch(background, /key: "Control", code: "ControlLeft"/, "draft cleanup must not use the rejected Ctrl+A replacement approach");
assert.match(background, /for \(let attempt = 1; attempt <= CDP_COMPOSER_PROMPT_ATTEMPTS; attempt \+= 1\)[\s\S]*?await sleep\(CDP_COMPOSER_PROMPT_RETRY_DELAY_MS\);[\s\S]*?await cdpClearComposerDraft\(tabId\);[\s\S]*?Input\.insertText[\s\S]*?current\.trim\(\) ===/, "each retry must wait, clear, insert, and verify the full prompt before sending");
assert.match(background, /current\.trim\(\) ===/, "the shortcut must verify the complete prompt before sending");
assert.match(background, /expectedText: text, composerText: actualText/, "a failed Composer verification must log both the exact requested prompt and observed draft");
assert.match(background, /firstDifferenceIndex/, "Composer mismatch diagnostics must report the first differing character position");
assert.match(background, /function normalizeComposerTextForComparison\(value\)[\s\S]*?normalize\("NFC"\)\.replace\(\/\\s\+\/gu, " "\)\.trim\(\)/, "Composer comparison must normalize Unicode form and whitespace before deciding whether the prompt matches");
assert.match(background, /normalizedComposerText === normalizedExpectedText/, "prompt submission must be based on the normalized full-text comparison");
assert.match(background, /console\.warn\("\[ResearchTube CDP\] Composer text mismatch; retrying replacement"/, "each retry mismatch must be visible in the browser console");
assert.match(background, /console\.warn\("\[ResearchTube CDP\] Composer prompt verification failed after all attempts", lastDiagnostic\)/, "a terminal Composer verification failure must print its text diagnostics to the console without creating an Errors entry");
assert.match(background, /key: "Backspace", code: "Backspace", windowsVirtualKeyCode: 8, nativeVirtualKeyCode: 8/, "Backspace must include both virtual-key codes");
assert.match(background, /key: "Delete", code: "Delete", windowsVirtualKeyCode: 46, nativeVirtualKeyCode: 46/, "Delete must be a verified fallback with both virtual-key codes");
assert.match(background, /composer\.selectionStart === 0 && composer\.selectionEnd === String\(composer\.value \?\? ''\)\.length/, "textarea cleanup must verify that all characters are selected");
assert.match(background, /normalize\(selection\.toString\(\)\) === normalize\(composer\.innerText/, "contenteditable cleanup must verify its full text selection");
assert.match(background, /cdpSendComposerText\(chatTab\.id, prompt\)/, "the shortcut must send the prepared prompt automatically");
assert.match(background, /CDP_SUBMIT_COMPOSER_FORM_EXPRESSION/, "the shortcut must submit the Composer form, not a detached page button");
assert.match(background, /form\.requestSubmit\(submitButton\)/, "the shortcut must invoke the Composer's form submission path");
assert.match(background, /form\.querySelector\('button\[type="submit"\]'\)/, "Composer submission must use its unique submit button");
assert.doesNotMatch(background, /dataset\.testid === 'send-button'|\^\(send\|send prompt\)/, "Composer submission must not depend on legacy button labels or test IDs");
assert.match(background, /cdpClearSentComposerDraft/, "a submitted Describe prompt must not remain as a stale Composer draft");
assert.match(background, /current\.trim\(\) === \$\{JSON\.stringify\(expectedText\)\}/, "draft cleanup must affect only the exact automation prompt");
assert.match(background, /CDP_SENT_DRAFT_CLEAR_CHECK_DELAYS_MS = \[500, 500, 1_000, 2_000\]/, "draft cleanup must recheck at roughly 0.5, 1, 2 and 4 seconds");
assert.match(background, /return "empty"/, "an empty Composer must remain eligible for later rehydration checks");
assert.match(background, /Composer draft changed by user; stopping cleanup/, "draft cleanup must stop when the user changes the Composer");
assert.match(background, /Input\.dispatchKeyEvent/, "draft cleanup must use browser-level input rather than an untrusted DOM edit");
assert.doesNotMatch(background, /Store this image in the Library\.|Store these images in the Library\./, "the Library flow must not insert a second storage instruction into Composer");
const prototype = background.slice(background.indexOf("const CDP_SERVICE_TAB_STORAGE_KEY"), background.indexOf("chrome.runtime.onInstalled"));
const libraryAttachmentFlow = background.slice(background.indexOf("async function cdpAttachFilesNow"), background.indexOf("function libraryStoreNow"));
assert.doesNotMatch(libraryAttachmentFlow, /Input\.insertText/, "the Library flow must not insert text into Composer");
assert.doesNotMatch(prototype, /document\.execCommand\('insertText'/);
assert.doesNotMatch(prototype, /uploadFile|DataTransfer|dragstart|ImageContent/);
assert.doesNotMatch(background, /chatgpt-service-tab\.png|setServiceTabFavicon|researchtube-service-favicon|favIconUrl/);
assert.deepEqual(parsedManifest.web_accessible_resources, [{ resources: ["media-viewer.html"], matches: ["https://chatgpt.com/*", "https://web-sandbox.oaiusercontent.com/*"] }], "only the local media viewer may be exposed to the ChatGPT card and its sandbox");
console.log("CDP service-tab prototype: ok");
