import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const background = await readFile(new URL("../background.js", import.meta.url), "utf8");

for (const tool of ["system_agent_status", "workspace_list", "workspace_stat", "workspace_mkdir", "workspace_move", "workspace_delete", "online_share_start", "online_share_status", "online_share_stop", "media_probe", "media_capture_frame", "media_capture_frame_get_task", "media_capture_frame_task_diagnostics", "media_capture_frame_cancel_task", "visual_map_create", "visual_map_get_task", "visual_map_cancel_task", "camera_list", "camera_capture_frame", "camera_record_video", "camera_record_audio", "camera_record_status", "camera_record_stop", "media_capture_screen", "media_image_crop", "media_image_show", "media_image_inspect", "clipboard_status", "clipboard_get", "clipboard_set", "media_load_workspace_image", "media_copy_workspace_path"]) {
  assert.match(background, new RegExp(`name: "${tool}"`), `${tool} must be published in tools/list`);
}
for (const tool of ["system_speech_list_voices", "system_speech_speak", "system_speech_status", "system_speech_cancel"]) {
  assert.match(background, new RegExp(`name: "${tool}"`), `${tool} must be published in tools/list`);
}
assert.match(background, /speech: \{ title: "Text to Speech"/, "speech tools must have a separate settings group");
for (const tool of ["library_store_start", "library_store_status", "library_store_cancel"]) {
  assert.match(background, new RegExp(`name: "${tool}"`), `${tool} must be published in tools/list`);
}
assert.match(background, /maxItems: 5/, "Library upload batches must be capped at five files");
assert.match(background, /libraryAvailability = "not_verified"/, "Library completion must not be claimed after ChatGPT submission");
assert.match(background, /presses Send without inserting any text into the Composer/, "Library storage must not create a second text instruction");
assert.match(background, /"\/internal\/library-store-files"/, "only the Agent may resolve workspace paths for CDP");
assert.match(background, /"\/tasks\/capture-frame"/);
assert.match(background, /"\/media\/image-crop"/);
assert.doesNotMatch(background, /"\/media\/workspace-image"/);
assert.match(background, /"\/media\/workspace-image-info"/, "the widget must obtain bounded metadata without image bytes");
for (const tool of ["youtube_download_get_formats", "youtube_download_get_task", "youtube_download_task_diagnostics", "youtube_download_cancel_task"]) {
  assert.match(background, new RegExp(`name: "${tool}"`), `${tool} must be published in tools/list`);
}
assert.match(background, /youtubeFormats: youtubeFormatsSchema/);
assert.match(background, /youtube_download_get_formats\.downloadFormats/);
assert.match(background, /afterEventId/);
assert.match(background, /const REQUIRED_AGENT_INTERFACE_VERSION = 67;/);
assert.match(background, /outputMode: \{ type: "string", enum: \["file", "speakers", "both"\]/, "speech must choose exactly one output mode");
assert.match(background, /voiceName: \{ type: "string", minLength: 1 \}/, "speech status must report the selected voice name");
assert.match(background, /engine: \{ type: "string", enum: \["googleTranslate", "windows"\], default: "googleTranslate" \}/, "Google Translate must be the default TTS engine");
assert.match(background, /lets Google detect the text language automatically/, "Google Translate must not require a target language");
assert.match(background, /saves the source MP3 returned to its page through CDP network events/, "Google Translate audio files must come from CDP network responses");
assert.match(background, /Network\.getResponseBody/, "Google Translate audio must be read from CDP network response bodies");
assert.match(background, /"jQ1olc"/, "Google Translate batchexecute TTS responses must be recognised");
assert.doesNotMatch(background, /chrome\.tabCapture/, "Google Translate must not require Chrome tab capture");
assert.match(background, /if \(input\.outputMode === "file"\) \{[\s\S]*?chrome\.tabs\.update\(tab\.id, \{ muted: true \}\)/, "file-only Google TTS must mute its tab during playback");
assert.match(background, /async function waitForGoogleTranslatePlaybackEnd/, "file-only Google TTS must observe source playback completion");
assert.match(background, /getAttribute\("aria-label"\) === "Stop listening"/, "playback completion must use Google Translate's Stop listening state");
assert.match(background, /if \(input\.outputMode === "file"\) await waitForGoogleTranslatePlaybackEnd\(tab\.id, controller\.signal\);/, "file-only Google TTS must wait for playback before saving and unmuting");
assert.match(background, /chrome\.tabs\.update\(active\.tabId, \{ muted: false \}\)/, "file-only Google TTS must restore its tab audio after saving");
assert.match(background, /let googleTranslateSpeechTabId = null/, "Google Translate must retain its background tab for the next request");
assert.match(background, /active: false/, "Google Translate must open in the background");
assert.match(background, /setValue\(""\);/, "Google Translate must clear an earlier source phrase before inserting the next one");
assert.match(background, /current\.value === text/, "Google Translate must verify the inserted source phrase before playback");
assert.doesNotMatch(background, /chrome\.tabs\.remove\(active\.tabId\)/, "Google Translate must not close the retained tab when playback ends or is cancelled");
assert.match(background, /waitForGoogleTranslateListenControl\(tab\.id, controller\.signal\);/, "Google Translate must wait until its listen button is enabled after processing the inserted text");
assert.match(background, /element\.getAttribute\("aria-disabled"\) !== "true"/, "Google Translate must treat aria-disabled listen controls as unavailable");
assert.match(background, /aria-label="Listen to source text"/, "Google Translate must target its explicit source-text listen control");
assert.match(background, /Clicked Google Translate source listen button with browser input/, "Google Translate must click its listen control through CDP browser input");
assert.match(background, /await cdpAttach\(tabId\);/, "Google Translate must attach CDP before clicking its listen control");
assert.match(background, /Emulation\.setFocusEmulationEnabled", \{ enabled: true \}/, "Google Translate must emulate focus without activating its tab");
assert.match(background, /Emulation\.setFocusEmulationEnabled", \{ enabled: false \}/, "Google Translate focus emulation must be cleared after the task");
assert.match(background, /Page\.setWebLifecycleState", \{ state: "active" \}/, "Google Translate must request an active lifecycle state to reduce background throttling");
assert.match(background, /googleTranslatePressListen\(tab\.id, controller\.signal, true\);[\s\S]*?if \(input\.outputMode === "speakers"\) \{[\s\S]*?google-translate-complete/, "speaker-only Google TTS must click Listen without requiring source-audio collection");
assert.match(background, /gap of at most 10 seconds are merged, but one range never exceeds 60 seconds/, "YouTube frame batches must use bounded hybrid section grouping");
assert.match(background, /targetFps is optional/, "camera recording must choose a default FPS when none is supplied");
assert.match(background, /name: "camera_record_audio"/, "audio-only camera recording must be published through the MCP tool registry");
assert.match(background, /enum: \["working", "stopping", "completed", "failed"\]/, "camera task schema must expose the graceful-stop state");
assert.doesNotMatch(background, /Before calling this tool, clearly tell the user that webcam video recording is about to begin\./, "camera recording must use the extension badge instead of an unseen chat warning");
assert.match(background, /exclusiveMinimum: 25, maximum: 120/, "camera recording FPS must accept native rates strictly above 25 through 120");
assert.match(background, /keys and fps preserve native rates such as 29\.97 or 59\.94/, "camera listing must preserve native non-integer rates");
assert.match(background, /selection: \{ type: "string", enum: \["uniform", "sceneDetect", "hybrid"\]/, "visual maps must publish uniform, scene-detect, and hybrid selectors");
assert.match(background, /sceneDetectThreshold: \{ type: "number", minimum: 0, maximum: 100, default: 10/, "visual maps must publish the native scdet percentage threshold");
assert.match(background, /FFmpeg's native scdet filter/, "the visual-map description must name native scdet");
assert.match(background, /sceneDetectThreshold must be a finite number from 0 to 100/, "the Extension must validate the native scdet threshold range");
assert.match(background, /empty interval uses its midpoint/, "the hybrid visual-map mode must fill scene-free intervals with their midpoint");
assert.match(background, /document\.selection === "hybrid" && document\.actualTotalFrames !== document\.maxTotalFrames/, "hybrid maps must contain exactly one selected point per requested interval");
assert.match(background, /de-duplicates changes closer than two seconds/, "the scene-detect contract must explain candidate filtering");
assert.match(background, /selection must be uniform, sceneDetect, or hybrid/, "the Extension must accept every visual-map selector before calling the Agent");
assert.match(background, /\["preparing", "detectingScenes", "extractingFrames"/, "the Extension must accept scene-detection task progress");
assert.match(background, /document\.selection !== input\.selection/, "the visual-map result must preserve and verify the requested selector");
assert.match(background, /"\/tasks\/visual-map"/, "visual maps must use the Agent task endpoint");
assert.match(background, /const RESEARCHTUBE_SERVER_DESCRIPTION =/, "the server must expose a bootstrap discovery description");
assert.match(background, /description: RESEARCHTUBE_SERVER_DESCRIPTION/, "serverInfo must publish its bootstrap discovery description");
assert.match(background, /ResearchTube is discoverable through functions\.exec lazy MCP-tool discovery/, "server description must name the bootstrap discovery path");
assert.match(background, /const RESEARCHTUBE_MCP_INSTRUCTIONS =/, "the MCP server must publish lazy-discovery guidance");
assert.match(background, /instructions: RESEARCHTUBE_MCP_INSTRUCTIONS/, "initialize must expose server-level MCP instructions");
assert.match(background, /do not infer that ResearchTube is unavailable/, "instructions must forbid inferring unavailability from tool visibility");
assert.match(background, /ResearchTube is available through functions\.exec with lazy MCP-tool discovery/, "instructions must name the client's deferred-tool discovery path");
assert.match(background, /tool === "library_store_status"/, "the Extension-local Library status poll must report an outcome to the Agent log");
assert.match(background, /\/mcp\/log\/\$\{tool\}/, "status reports must identify the tool without sending its inputs");
assert.match(background, /availableBytes/);
assert.match(background, /operatingSystem.*release.*version.*architecture/s);
assert.match(background, /function normalizeWorkspacePath\(/);
assert.match(background, /source.*destination.*never overwrites/s);
assert.match(background, /Non-empty directories are refused/);
assert.match(background, /ffprobeFileSizeBytes/);
assert.match(background, /author, creation time, location\/GPS/);
assert.match(background, /CAPTURE_FRAME_WIDGET_URI/);
assert.match(background, /resources\/read/);
assert.match(background, /text\/html;profile=mcp-app/);
assert.doesNotMatch(background, /captureFrameImageBase64/);
assert.match(background, /localAgentImageUrl/, "the widget must keep image bytes out of MCP metadata");
assert.match(background, /\$\{port\}\/\$\{encodedWorkspacePath\}/, "local image URL must place the logical workspace path directly after the Agent port");
assert.doesNotMatch(background, /widget-image\?path=/, "the local image URL must not use a query-string path parameter");
assert.match(background, /mcpToolPreferences/, "tool availability must be persisted by exact MCP tool name");
assert.match(background, /newToolsEnabledByDefault/, "new MCP tools must have a configurable default state");
assert.match(background, /TOOL_DISABLED/, "a stale ChatGPT tool schema must receive a clear disabled-tool result");
assert.match(background, /working: \{ text: "\?", color: \[0, 0, 0, 0\]/, "ordinary MCP work must use a transparent question-mark badge");
assert.doesNotMatch(background, /researchtube-busy-/, "ordinary MCP work must retain the original toolbar icon");
assert.match(background, /state === "working" && cameraRecordingBadgeKind/, "a camera recording badge must take precedence over the general MCP hourglass");
assert.match(background, /showInChat defaults to false/);
assert.match(background, /never render a widget themselves/, "creation tools must not create blank static-template iframes");
assert.match(background, /After a successful result, call media_image_show/, "showInChat must route presentation through the dedicated display tool");
assert.match(background, /A successful result means the card has already been shown; do not call it again for the same file/, "the display tool must prevent duplicate retries");
assert.match(background, /text: "Workspace media shown\."/, "the display tool must return an explicit compact success result to the model");
assert.match(background, /Independently validate one PNG, JPEG, or WebP image/, "image inspection must be distinct from generic workspace stat");
assert.equal((background.match(/"openai\/outputTemplate": CAPTURE_FRAME_WIDGET_URI/g) || []).length, 1, "only the explicit workspace-image display tool may declare the widget template");
assert.doesNotMatch(background, /researchtube_copy_capture_frame_image/);
assert.doesNotMatch(background, /researchtube_download_capture_frame/);
assert.doesNotMatch(background, /chrome\.downloads\.download/);
assert.match(background, /chrome\.offscreen\.createDocument/);
assert.match(background, /capture-frame-offscreen\.html/);
assert.match(background, /Frames are saved in captures/, "batch frame extraction must save files in Workspace without automatic display");
assert.match(background, /name: "media_capture_frame_task_diagnostics"/, "failed YouTube frame batches must expose bounded diagnostics");
assert.match(background, /failedSection/, "failed YouTube frame batches must identify the failed partial section");
assert.match(background, /PO-token-provider state/, "frame diagnostics must identify PO-token-provider availability");
assert.match(background, /Signed media URLs, PO Tokens, cookies, host paths/, "frame diagnostics must redact sensitive yt-dlp output");
assert.doesNotMatch(background, /Public HTTPS URL served only by the Agent's image-only Cloudflare Quick Tunnel/);
assert.match(background, /outputPath/);
assert.match(background, /cloudflared/);
assert.match(background, /online_share_start/);
assert.match(background, /online_share_status/);
assert.match(background, /online_share_stop/);
assert.match(background, /online: \{ title: "Online Share"/, "online sharing must have its own Settings group");
assert.match(background, /verifyExternal=true/, "the public share must expose explicit external probing");
assert.match(background, /probePath/, "a verified folder share must use a selected image probe path");
assert.match(background, /externallyReachable/, "the public share must distinguish tunnel start from external reachability");
assert.match(background, /wsrv\.nl/, "external verification must name its independent image proxy");
assert.match(background, /single-file share/, "the public share must support an exact-file mode");
assert.doesNotMatch(background, /saveToLibrary/);
assert.doesNotMatch(background, /delivery\.workspacePath/);
assert.match(background, /--download-sections/);
assert.match(background, /youtube_download_get_formats/);
assert.doesNotMatch(background, /name: "youtube_get_download_formats"/);
assert.match(background, /status: "rejected"/, "expected input and state errors must be ordinary structured results");
assert.match(background, /isError: false/, "expected input and state errors must not be raised as MCP errors");
console.log("workspace tools contract: ok");
